version: '3.8'

services:
  # Nosso banco de dados (já estava aqui)
  postgres_db:
    image: postgres:15-alpine
    container_name: uptime_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: api_monitor_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # Nova adição: A nossa API
  api:
    build: .
    container_name: uptime_api
    restart: always
    ports:
      - "3000:3000"
    environment:
      # O container da API se conecta ao container do banco pelo nome do serviço (postgres_db)
      DATABASE_URL: "postgresql://admin:admin123@postgres_db:5432/api_monitor_db?schema=public"
    volumes:
      # Espelha o seu código local para dentro do container (permite o nodemon funcionar)
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - postgres_db

volumes:
  pgdata: