# A chave exclusiva do projeto e o nome da organização gerados no painel do SonarCloud
sonar.projectKey=joaogsribeiro_uptime-core-api
sonar.organization=joaogsribeiro

# Onde está o código-fonte
sonar.sources=src

# O que NÃO analisar (para não poluir as métricas)
sonar.exclusions=node_modules/**, **/*.test.js, src/config/database.js

# Configurações de Testes e Cobertura
sonar.tests=tests
sonar.test.inclusions=**/*.test.js
sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.language=js